parameters:
    sonatra_block.twig.extension.base.class: Sonatra\Bundle\BlockBundle\Twig\Extension\BlockExtension
    sonatra_block.twig.renderer.base.class: Sonatra\Bundle\BlockBundle\Twig\Block\TwigRenderer
    sonatra_block.twig.engine.base.class: Sonatra\Bundle\BlockBundle\Twig\Block\TwigRendererEngine

    sonatra_block.twig.resources:

services:
    sonatra_block.twig.extension:
        public: false
        class: '%sonatra_block.twig.extension.base.class%'
        arguments: ['@sonatra_block.twig.renderer', '@sonatra_block.factory', '@sonatra_block.registry']
        tags: [ { name: twig.extension } ]

    sonatra_block.twig.renderer:
        public: false
        class: '%sonatra_block.twig.renderer.base.class%'
        arguments: ['@sonatra_block.twig.engine']

    sonatra_block.twig.engine:
        public: false
        class: '%sonatra_block.twig.engine.base.class%'
        arguments: ['%sonatra_block.twig.resources%']
